image: node:18

stages:
  - install
  - build
  - deploy

variables:
  DOMAIN: "shavaz"
  NGINX_SITES_AVAILABLE: "/etc/nginx/sites-available"
  NGINX_SITES_ENABLED: "/etc/nginx/sites-enabled"
  WWW_ROOT: "/var/www/${DOMAIN}/dev/frontend"

install_dependencies:
  stage: install
  only:
    - release
  script:
    - pwd
    - npm install

build:
  stage: build
  only:
    - release
  script:
    - npm ci
    - ls
    - npm run build
  artifacts:
    paths:
      - .output/ 

deploy:
  stage: deploy
  only:
    - release
  script:
    - BRANCH_NAME=$(echo $CI_COMMIT_REF_NAME | sed 's/\//_/g')
    - DEPLOY_DIR="${WWW_ROOT}/${BRANCH_NAME}"
    - NGINX_FILE_NAME=${BRANCH_NAME}.frontend.dev
    - NGINX_CONF="${NGINX_SITES_AVAILABLE}/${NGINX_FILE_NAME}"

    # Create Nginx config file for the branch with actual values
    - |
      sudo bash -c "cat > $NGINX_CONF" << EOF

      server {
      listen 80;
      listen [::]:80;
      index index.html;
      server_name $NGINX_FILE_NAME.shvz.ir;

      location / {
          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade \$http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host \$host;
          proxy_cache_bypass \$http_upgrade;
        }
      }
      EOF

    - if [ -L "${NGINX_SITES_ENABLED}/${NGINX_FILE_NAME}" ]; then
        sudo rm "${NGINX_SITES_ENABLED}/${NGINX_FILE_NAME}";
      fi

    # Link the Nginx config file to sites-enabled
    - sudo ln -s $NGINX_CONF ${NGINX_SITES_ENABLED}/${NGINX_FILE_NAME}

    # Create the directory structure for the branch
    - sudo mkdir -p $DEPLOY_DIR

    - sudo rsync -av --delete .output/ $DEPLOY_DIR
    #- sudo rsync -av --delete .output/public/ $DEPLOY_DIR

    #- rsync -avz --delete-after


    # Check the Nginx configuration
    - sudo nginx -t

    # If Nginx config is OK, reload Nginx
    - if [ $? -eq 0 ]; then sudo systemctl reload nginx; else echo "Nginx configuration test failed" && exit 1; fi


    - echo "Deployment complete."
  environment:
    name: production
    url: https://$NGINX_FILE_NAME.shvz.ir

